backend:
  name: git-gateway
  branch: main


publish_mode: editorial_workflow

media_folder: "public/images" 
public_folder: "/images" 

collections:
  - name: "blog" 
    label: "Posts" 
    folder: "src/pages/blog" 
    create: true 
    slug: "{{slug}}" 
    fields: 
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "../../layouts/BlogPostLayout.astro",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
